
spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7777

management:
  endpoint:
    gateway:
      enabled :true
  endpoints:
    web:
      exposure:
        include: "*"